version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: gradle test
      - run:
          name: Run integration tests
          command: gradle integrationTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: build/reports/tests